# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm start ci

branches:
  only:
    - master

skip_tags: true

matrix:
  fast_finish: true

cache:
  - node_modules
  - %APPDATA%\npm-cache

build: off
