# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm start ci

branches:
  only:
    - master

# do not build on tags (GitHub only)
skip_tags: true

# immediately finish build once one of the jobs fails
matrix:
  fast_finish: true

# fetch repository as zip archive
shallow_clone: true
clone_depth: 1

cache:
  # global npm modules
  - "%APPDATA%\\npm\\node_modules -> package.json"
  # npm cache
  - "%APPDATA%\\npm-cache -> package.json"
  # local npm modules
  - node_modules -> package.json

# don't actually build
build: off
